# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-08-15 05:40
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='data_workorder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sql_title', models.CharField(max_length=100, verbose_name='\u5de5\u5355\u6807\u9898')),
                ('sql_memo', models.TextField(verbose_name='\u5de5\u5355\u63cf\u8ff0')),
                ('sql_user', models.CharField(max_length=25, verbose_name='\u63d0\u4ea4\u8005')),
                ('sql_date', models.DateTimeField(verbose_name='\u63d0\u4ea4\u65f6\u95f4')),
                ('sql_status', models.CharField(max_length=25, verbose_name='\u5904\u7406\u72b6\u6001')),
                ('sql_ret', models.TextField(blank=True, null=True, verbose_name='\u5904\u7406\u529e\u6cd5\u548c\u7ed3\u679c')),
                ('sql_action_user', models.ManyToManyField(to=settings.AUTH_USER_MODEL, verbose_name='\u5904\u7406\u4eba')),
            ],
            options={
                'verbose_name': 'data',
                'verbose_name_plural': 'data',
            },
        ),
        migrations.CreateModel(
            name='mywork',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mywork_title', models.CharField(max_length=100, verbose_name='\u5de5\u5355\u6807\u9898')),
                ('mywork_memo', models.TextField(verbose_name='\u5de5\u5355\u63cf\u8ff0')),
                ('mywork_user', models.CharField(max_length=25, verbose_name='\u63d0\u4ea4\u8005')),
                ('mywork_date', models.DateTimeField(verbose_name='\u63d0\u4ea4\u65f6\u95f4')),
                ('mywork_status', models.CharField(max_length=25, verbose_name='\u5904\u7406\u72b6\u6001')),
                ('mywork_ret', models.TextField(blank=True, null=True, verbose_name='\u5904\u7406\u529e\u6cd5\u548c\u7ed3\u679c')),
                ('mywork_action_user', models.ManyToManyField(to=settings.AUTH_USER_MODEL, verbose_name='\u5904\u7406\u4eba')),
            ],
            options={
                'verbose_name': '\u5de5\u5355\u5217\u8868',
                'verbose_name_plural': '\u5de5\u5355\u5217\u8868',
            },
        ),
        migrations.CreateModel(
            name='web_workorder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('web_title', models.CharField(max_length=100, verbose_name='\u5de5\u5355\u6807\u9898')),
                ('web_memo', models.TextField(verbose_name='\u5de5\u5355\u63cf\u8ff0')),
                ('web_user', models.CharField(max_length=25, verbose_name='\u63d0\u4ea4\u8005')),
                ('web_date', models.DateTimeField(verbose_name='\u63d0\u4ea4\u65f6\u95f4')),
                ('web_status', models.CharField(max_length=25, verbose_name='\u5904\u7406\u72b6\u6001')),
                ('web_ret', models.TextField(blank=True, null=True, verbose_name='\u5904\u7406\u529e\u6cd5\u548c\u7ed3\u679c')),
                ('web_create_svn_status', models.CharField(blank=True, choices=[(b'on', '\u662f'), (b'off', '\u5426')], default=b'off', max_length=10, null=True, verbose_name='\u662f\u5426\u521b\u5efasvn')),
                ('web_action_user', models.ManyToManyField(to=settings.AUTH_USER_MODEL, verbose_name='\u5904\u7406\u4eba')),
            ],
            options={
                'verbose_name': 'web',
                'verbose_name_plural': 'web',
            },
        ),
    ]
