# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-08-25 09:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workorder', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mywork',
            name='mywork_type',
            field=models.CharField(choices=[(b'web', 'web\u76f8\u5173'), (b'sql', '\u6570\u636e\u5e93\u76f8\u5173'), (b'svn', 'svn\u76f8\u5173'), (b'permission', '\u65b0\u589e\u6743\u9650'), (b'other', '\u5176\u4ed6'), (b'conf_change', '\u914d\u7f6e\u6587\u4ef6\u4fee\u6539'), (b'permission_change', '\u6743\u9650\u53d8\u66f4'), (b'sql_change)', '\u6570\u636e\u5e93\u53d8\u66f4'), (b'other_change', '\u5176\u4ed6\u53d8\u66f4'), (b'problem', '\u6545\u969c\u7533\u62a5')], default=b'web', max_length=100, verbose_name='\u5de5\u5355\u7c7b\u578b'),
        ),
    ]
