# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-08-25 09:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workorder', '0002_mywork_mywork_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='web_workorder',
            name='web_name',
            field=models.CharField(default=1, max_length=100, verbose_name='\u9879\u76ee\u540d'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='web_workorder',
            name='web_path',
            field=models.CharField(default=1, max_length=100, verbose_name='\u9879\u76ee\u8def\u5f84'),
            preserve_default=False,
        ),
    ]
