# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-08-25 10:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workorder', '0003_auto_20170825_1752'),
    ]

    operations = [
        migrations.AddField(
            model_name='mywork',
            name='other_id',
            field=models.CharField(default=1, max_length=1000, verbose_name='\u8be6\u7ec6id'),
            preserve_default=False,
        ),
    ]
