# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-08-25 11:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workorder', '0004_mywork_other_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='web_workorder',
            name='domain_time',
            field=models.CharField(default=1, max_length=40, verbose_name='\u57df\u540d\u89e3\u6790\u65f6\u95f4'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='web_workorder',
            name='web_create_cdn_status',
            field=models.CharField(blank=True, choices=[(b'on', '\u662f'), (b'off', '\u5426')], default=b'off', max_length=10, null=True, verbose_name='\u662f\u5426\u521b\u5efacdn'),
        ),
        migrations.AddField(
            model_name='web_workorder',
            name='web_create_https_status',
            field=models.CharField(blank=True, choices=[(b'on', '\u662f'), (b'off', '\u5426')], default=b'off', max_length=10, null=True, verbose_name='\u662f\u5426\u9700\u8981https'),
        ),
    ]
