# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-08-28 11:08
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('workorder', '0005_auto_20170825_1936'),
    ]

    operations = [
        migrations.CreateModel(
            name='svn_workorder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('svn_title', models.CharField(max_length=100, verbose_name='\u5de5\u5355\u6807\u9898')),
                ('svn_name', models.CharField(max_length=100, verbose_name='\u5de5\u5355\u6807\u9898')),
                ('svn_memo', models.TextField(verbose_name='\u5de5\u5355\u63cf\u8ff0')),
                ('svn_user', models.CharField(max_length=25, verbose_name='\u63d0\u4ea4\u8005')),
                ('svn_time', models.DateTimeField(verbose_name='\u63d0\u4ea4\u65f6\u95f4')),
                ('svn_status', models.CharField(max_length=25, verbose_name='\u5904\u7406\u72b6\u6001')),
                ('svn_ret', models.TextField(blank=True, null=True, verbose_name='\u5904\u7406\u529e\u6cd5\u548c\u7ed3\u679c')),
                ('svn_action_user', models.ManyToManyField(to=settings.AUTH_USER_MODEL, verbose_name='\u5904\u7406\u4eba')),
            ],
            options={
                'verbose_name': 'svn\u5de5\u5355',
                'verbose_name_plural': 'svn\u5de5\u5355',
            },
        ),
        migrations.AlterModelOptions(
            name='data_workorder',
            options={'verbose_name': '\u6570\u636e\u5e93\u5de5\u5355', 'verbose_name_plural': '\u6570\u636e\u5e93\u5de5\u5355'},
        ),
    ]
