# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-08-28 11:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workorder', '0006_auto_20170828_1908'),
    ]

    operations = [
        migrations.AddField(
            model_name='svn_workorder',
            name='svn_create_pangu_status',
            field=models.CharField(blank=True, choices=[(b'on', '\u662f'), (b'off', '\u5426')], default=b'off', max_length=10, null=True, verbose_name='\u76d8\u53e4\u662f\u5426\u521b\u5efa\u5bf9\u5e94'),
        ),
        migrations.AlterField(
            model_name='svn_workorder',
            name='svn_name',
            field=models.CharField(max_length=100, verbose_name='SVN\u9879\u76ee\u540d'),
        ),
    ]
