# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-08-28 11:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workorder', '0007_auto_20170828_1913'),
    ]

    operations = [
        migrations.AddField(
            model_name='svn_workorder',
            name='domain_time',
            field=models.CharField(default=1, max_length=40, verbose_name='\u57df\u540d\u89e3\u6790\u65f6\u95f4'),
            preserve_default=False,
        ),
    ]
